apiVersion: v1
kind: Service
metadata:
  name: noteziee-db-service
  labels:
    app: noteziee
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: noteziee
  type: NodePort
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sql-trigger-sc
provisioner: k8s.io/hostpath
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sql-trigger-pv-volume
  labels:
    type: local
spec:
  storageClassName: sql-trigger-sc
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/sql-trigger"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sql-trigger-pv-claim
spec:
  storageClassName: sql-trigger-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: noteziee-db-sc
provisioner: k8s.io/hostpath
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: noteziee-db-pv-volume
  labels:
    type: local
spec:
  storageClassName: noteziee-db-sc
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/noteziee-db"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: noteziee-db-pv-claim
spec:
  storageClassName: noteziee-db-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi      
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: noteziee-db-deployment
  labels:
    app: noteziee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: noteziee
  template:
    metadata:
      labels:
        app: noteziee
    spec:
      containers:
        - env:
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "1"
            - name: MYSQL_DATABASE
              value: CommentDB
            - name: MYSQL_PASSWORD
              value: uitcisco
            - name: MYSQL_USER
              value: noteziee
          image: mysql:latest
          name: noteziee
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: sql-trigger-persistent-storage
              mountPath: "/docker-entrypoint-initdb.d"
            - name: noteziee-db-persistent-storage
              mountPath: "/var/lib/mysql"
      volumes:
        - name: sql-trigger-persistent-storage
          persistentVolumeClaim:
            claimName: sql-trigger-pv-claim
        - name: noteziee-db-persistent-storage
          persistentVolumeClaim:
            claimName: noteziee-db-pv-claim