apiVersion: v1
kind: Service
metadata:
  name: noteziee-db-service
  labels:
    app: noteziee
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: noteziee
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: noteziee-db-deployment
  labels:
    app: noteziee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: noteziee
  template:
    metadata:
      labels:
        app: noteziee
    spec:
      containers:
      - image: suppi147/noteziee-db
        name: noteziee
        ports:
        - containerPort: 3306